=head1 Dist::Zilla::PluginBundle::GopherRepellent

I<< Keep those pesky gophers away from your dists! >>

PluginBundles for building perl distributions
with Dist::Zilla and Pod::Weaver.  

I built my own
after my ini files started getting unruly.

It also made sense to me to build a separate
PluginBundle for C<$work> which could use this one
and then set a few attributes.

=head1 SEE ALSO

=over

=item * The POD in the actual modules for more information.

=item * The Secret of Monkey Island (E<copy> Lucas Arts)
- the inspiration for the name of this bundle

=back

=cut
